# This is the default configuration for the entire system.
#
# If you add a new configuration value, you must add its default value as an
# entry in this file - this is automatically checked at runtime if the Python
# variable Config.ALLOW_EMPTY_OPTIONS is False, which it is by default, so if
# you try to get a configuration that doesn't exist in the default file, you'll
# throw an Exception.

type: config

allow_shutdown: true

autostart: true

audio:
  input:
    aplay_binary: ''
    average:
      chunk_size: 1024
      group_size: 0
      window_size: 0
    enable: true
    frames_per_buffer: 4096
    index: -1
    name: ''
    periodsize: 160
    sample_bytes: 2
    sample_rate: 4000
    verbose: false

    levels:
      silent: -37
      quiet: -25
      medium: -15
      loud: 0

  output:
    aplay_binary: ''
    chunk_size: 1024
    enable: true
    frames_per_buffer: 1024
    index: -1
    name: ''
    route: audio
    use_aplay: false

control_program:
  enable: true
  use_tk: true

diagnostics:
  dump_unused_configs: false
  dump_startup_times: false

discovery:
  port: 1238
  timeout: 0.10

git:
  user: rec
  project: echomesh

headless: false

load_module:
  analyse: true
  pi3d: true
  pyaudio: true
  numpy: true

logging:
  file: ""
  format: "%(asctime)s %(levelname)s: %(name)s: %(message)s"
  level: info

opening_sleep: 0.5

pi3d:
  aspect: 60.0
  background: [0, 0, 0, 0]  # Red, green, blue, alpha.
  depth: 24
  dimensions: null  # Can be a 4-tuple: x, y, width, height.
  far: null
  frames_per_second: 30
  full_screen: true
  near: null
  tk: False
  window_title: ''

score:
  file: ''

sequence:
  delay: 5.0

shorten:
  enable: true
  include_url: true
  index_file: /home/tom/shortenIndex.txt
  prefix: e
  url: "http://ax.to"
  use_index_url: true

update_interval: 0

version: 0.8