# This is the default configuration for Darwin (Mac OS/X) systems.

type: config

audio:
  input:
    enable: false

  output:
    enable: false

control_program:
  enable: true

pi3d:
  enable: false
