network:
  client:
    binary: /development/echomesh/code/cpp/Builds/MacOSX/build/Release/echomesh-client.app/Contents/MacOS/echomesh-client

midi:
  input:
    name: from Max

  output:
    name: to Max

light:
  visualizer:
    visualizer_closes_echomesh: true