network:
  client:
    start: true
    allow_reuse_address: true
    binary: /development/echomesh/code/cpp/Builds/MacOSX/build/Debug/echomesh-client.app/Contents/MacOS/echomesh-client

---
debug: false
network:
  client: {start: false}
