type: config

allow_shutdown: true

audio:
  library: pyaudio

  output:
    route: audio

  input:
    samplerate: 8000
    name: AK5370
    periodsize: 160
    verbose: false

    chunksize: 1024
    grouping_window: 2
    moving_window: 2

    levels:
      silent: -37
      quiet: -25
      medium: -15
      loud: 0

discovery:
  port: 1238
  timeout: 0.10

display:
  dimensions: [960, 0, 960, 600, 0]
  frames_per_second: 10
  full_screen: true
  library: pi3d

git:
  user: rec
  project: echomesh

logging:
#  file: ~/log/echomesh.log  # Uncomment to create a file
  level: info

shorten:
  enable: true
  include_url: true
  index_file: /home/tom/shortenIndex.txt
  prefix: e
  url: "http://ax.to"
  use_index_url: true