Chairman:
  control_program: false
  score:
    file: test.yml
  audio: {input: {verbose: false, use_default: true, enable: false},
          output: {use_aplay: true}}
  display: {enable: false}

hofmann:
  headless: true
  score: {enable: true}

Treasurer:
  control_program: true
  score:
    file: marek.yml
